<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Circlical\VisualCaptcha\CaptchaSession'                       => __DIR__ . '/src/Circlical/VisualCaptcha/CaptchaSession.php',
  'Circlical\VisualCaptcha\Controller\CaptchaController'         => __DIR__ . '/src/Circlical/VisualCaptcha/Controller/CaptchaController.php',
  'Circlical\VisualCaptcha\Form\Captcha\VisualCaptcha'           => __DIR__ . '/src/Circlical/VisualCaptcha/Form/Captcha/VisualCaptcha.php',
  'Circlical\VisualCaptcha\Form\View\Helper\VisualCaptchaHelper' => __DIR__ . '/src/Circlical/VisualCaptcha/Form/View/Helper/VisualCaptchaHelper.php',
  'Circlical\VisualCaptcha\Module'                               => __DIR__ . '/src/Circlical/VisualCaptcha/Module.php',
);
